#!/usr/bin/with-contenv bash

# agree EULA
EULA_FILE="/data/eula.txt"
if [ -f "${EULA_FILE}" ]; then
    if grep -q "eula=false" "${EULA_FILE}"; then
        sed -i -e s/"eula=false"/"eula=true"/ "${EULA_FILE}"
    fi
else
	echo "eula=true" > "${EULA_FILE}"
fi

PAPER_RELEASE="1.15.2-b99"
if [ ! -f "/data/paper.jar"]; then
	curl -o /data/paper.jar -L "https://yivesmirror.com/files/paper/Paper-${PAPER_RELEASE}.jar"
fi

# permissions
chown -R abc:abc \
	/data \
	/data/*
